Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using BoardGames.Validators;

namespace BoardGames.Models
{
    public partial class Game
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Name is required")]
        [UniqueGameName]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }
        
        [Required(ErrorMessage = "Number of players is required")]
        public string NoOfPlayers { get; set; }
        
        [Required(ErrorMessage = "Age is required")]
        public string Age { get; set; }
        
        [Required(ErrorMessage = "Average game time is required")]
        public string AverageGameTime { get; set; }
        
        [Range(1, 6, ErrorMessage = "Randomness must be number between 1-6")]
        [Display(Name = "Randomness")]
        public int? Randomness { get; set; }
        
        [Range(1, 6, ErrorMessage = "Interaction must be number between 1-6")]
        [Display(Name = "Interaction")]
        public int? Interaction { get; set; }
        
        [Range(1, 6, ErrorMessage = "Complexity must be number between 1-6")]
        [Display(Name = "Complexity")]
        public int? Complexity { get; set; }
        
        public int? CategoryId { get; set; }
        
        public int? PublisherId { get; set; }
        public DateTime? Added { get; set; }
        public DateTime? Edited { get; set; }

        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}

ViewModels/IndexHeaderViewModel.cs
namespace BoardGames.ViewModels
{
    public class IndexHeaderViewModel
    {
        public string ControllerName { get; set; }
        
        public IndexHeaderViewModel(string controllerName)
        {
            ControllerName = controllerName;
        }
    }
}

Controllers/AuthController.cs
using System.Threading.Tasks;
using System.Web;
using BoardGames.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoardGames.Controllers
{
    public class AuthController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AuthController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        
        [Route("auth/register")]
        public IActionResult Register()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("auth/register")]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser
                {
                    UserName = model.Email,
                    Email = model.Email
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "Home");
                }
                
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }
        
        [Route("auth/login")]
        public IActionResult Login([FromQuery(Name = "ReturnUrl")] string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("auth/login")]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
            
                if (result.Succeeded)
                {
                    if (Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("index", "Home");
                    }
                }
                
                ModelState.AddModelError(string.Empty, "Invalid email or password");
            }

            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("index", "Home");
        }
    }
}

Controllers/GamesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BoardGames.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoardGames.Controllers
{
    public class Games : Controller
    {
        private readonly AppDbContext _dbContext;

        public Games(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Route("games")]
        public async Task<IActionResult> Index(string name)
        {
            var games = (from g in _dbContext.Game
                         join category in _dbContext.Category on g.CategoryId equals category.Id
                         join publisher in _dbContext.Publisher on g.PublisherId equals publisher.Id
                         select new Game
                         {
                             Id = g.Id,
                             Name = g.Name,
                             Description = g.Description,
                             NoOfPlayers = g.NoOfPlayers,
                             Age = g.Age,
                             AverageGameTime = g.AverageGameTime,
                             Randomness = g.Randomness,
                             Interaction = g.Interaction,
                             Complexity = g.Complexity,
                             Category = category,
                             Publisher = publisher
                         });

            if (!String.IsNullOrEmpty(name))
            {
                games = games.Where(g => g.Name.ToLower().Contains(name.ToLower()));
            }

            TempData["SearchString"] = name ?? "";
            return View(await games.ToListAsync());
        }

        [Route("boardgame/{id}")]
        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var game = _dbContext.Game.First(g => g.Id == id);
            game.Category = _dbContext.Category.First(category => category.Id == game.CategoryId);
            game.Publisher = _dbContext.Publisher.First(publisher => publisher.Id == game.PublisherId);

            return View(game);
        }

        [Route("games/add")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            
            var categories = _dbContext.Category.ToList();
            ViewData["Categories"] = categories;
                        
            var publishers = _dbContext.Publisher.ToList();
            ViewData["Publishers"] = publishers;
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("games/add")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(GameCreateViewModel game)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _dbContext.Add(game);
                    await _dbContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ViewData["ErrorMessage"] =
                    "Create failed. Try again.";
            }

            var categories = _dbContext.Category.ToList();
            ViewData["Categories"] = categories;
                    
            var publishers = _dbContext.Publisher.ToList();
            ViewData["Publishers"] = publishers;
            
            return View(game);
        }
        
        [Route("boardgame/edit/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            var gameToUpdate = await _dbContext.Game.FirstOrDefaultAsync(s => s.Id == id);
            
            var categories = _dbContext.Category.ToList();
            ViewData["Categories"] = categories;
                    
            var publishers = _dbContext.Publisher.ToList();
            ViewData["Publishers"] = publishers;
            
            return View(gameToUpdate);
        }
        
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Route("boardgame/edit/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditGame(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameToUpdate = await _dbContext.Game.FirstOrDefaultAsync(s => s.Id == id);
            if (await TryUpdateModelAsync<Game>(
                gameToUpdate,
                "",
                g => g.Name,
                g => g.Description,
                g => g.NoOfPlayers,
                g => g.AverageGameTime,
                g => g.Age,
                g => g.Randomness,
                g => g.Interaction,
                g => g.Complexity,
                g => g.CategoryId,
                g => g.PublisherId)
            )
            {
                try
                {
                    await _dbContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    Console.WriteLine(ex.ToString());
                    @ViewData["ErrorMessage"] = "Edit failed. Try again.";
                }
            }
            
            var categories = _dbContext.Category.ToList();
            ViewData["Categories"] = categories;
                    
            var publishers = _dbContext.Publisher.ToList();
            ViewData["Publishers"] = publishers;

            return View(gameToUpdate);
        }

        [Route("boardgame/delete/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _dbContext.Game
                .AsNoTracking()
                .FirstOrDefaultAsync(g => g.Id == id);

            if (game == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again.";
            }

            return View(game);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("boardgame/delete/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _dbContext.Game.FindAsync(id);
            if (game == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _dbContext.Game.Remove(game);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new {id = id, saveChangesError = true});
            }
        }
    }
}

Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using BoardGames.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BoardGames.Controllers
{
    public class UsersController : Controller
    {
        
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        
        public UsersController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        
        [Route("/admin/users")]
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _userManager.Users;
            var roles = _roleManager.Roles;
            
            UsersIndexViewModel viewModel = new UsersIndexViewModel(users, roles);
            
            return View(viewModel);
        }
        
        [HttpPost]
        [Route("/admin/add-user-to-role")]
        public async Task<IActionResult> AddUserToRoleAction([FromBody]Payload payload)
        {
            var user = await _userManager.FindByIdAsync(payload.UserId);
            
            var userRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, userRoles.ToArray());
            
            var result = await _userManager.AddToRoleAsync(user, payload.RoleName);

            if (result.Succeeded)
            {
                return Ok(new { status = true, msg = "User successfully added to role" });
            }
                return BadRequest(new { status = false, msg = "An error has occurred", error = result.Errors});
            
        }
    }
    
    public class Payload
    {
        public string UserId { get; set; }
        public string RoleName { get; set; }
    }
}

Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - BoardGames Auth</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="~/css/site.css"/>
  <script src="https://kit.fontawesome.com/1c64bcf471.js" crossorigin="anonymous"></script>
</head>
<body class="bg-dark m-0 vh-100">
<div class="container-fluid h-100">
  <div class="row h-100">
    <div class="auth-bg col-6">
    </div>
    <div class="col-6 pl-5 pr-5 text-white d-flex flex-column justify-content-center">
      <header class="mt-5 mb-5">
        <h1>
          @ViewData["Title"]
          <small class="text-muted">or</small>
        </h1>
        <a asp-area="" asp-controller="Home" asp-action="Index"><span class="fas fa-arrow-left mr-2"></span>Back to website</a>
      </header>
      
      @RenderBody()
    </div>
  </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_GamesTable.cshtml
@model BoardGames.ViewModels.GamesTableViewModel;

<table class="table">
  <caption>@Model.Caption</caption>
  <thead class="thead-dark">
  <tr>
    <th scope="col">No.</th>
    <th scope="col">Name</th>
    <th scope="col">Category</th>
    <th scope="col">Publisher</th>
    <th scope="col">No. of players</th>
    <th scope="col">Age</th>
    @if (@Model.Editable && User.IsInRole("Admin"))
    {
      <th scope="col">Action</th>
    }
  </tr>
  </thead>
  <tbody>
  @if (Model.Games.Count != 0)
  {
    @foreach (var (game, index) in Model.Games.Select((v, i) => (v, i += 1)))
    {
      <tr>
        <th scope="row" class="align-middle">@index</th>
        <td class="align-middle">
          <a asp-area="" asp-controller="Games" asp-action="Detail" asp-route-id="@game.Id">@game.Name</a>
        </td>
        <td class="align-middle">
          <a asp-area="" asp-controller="Categories" asp-action="Detail" asp-route-id="@game.Category.Id">@game.Category.Name</a>
        </td>
        <td class="align-middle">
          <a asp-area="" asp-controller="Publishers" asp-action="Detail" asp-route-id="@game.Publisher.Id">@game.Publisher.Name</a>
        </td>
        <td class="align-middle">@game.NoOfPlayers</td>
        <td class="align-middle">@game.Age</td>
        @if (@Model.Editable && User.IsInRole("Admin"))
        {
          <td class="align-middle">
            <a asp-area="" asp-controller="Games" asp-action="Edit" asp-route-id="@game.Id" class="btn btn-primary">
              <span class="fas fa-edit"></span>
            </a>
            <a asp-area="" asp-controller="Games" asp-action="Delete" asp-route-id="@game.Id" class="btn btn-danger">
              <span class="fas fa-trash"></span>
            </a>
          </td>
        }
      </tr>
    }
  }
  else
  {
    <tr>
      <td class="text-center" colspan="@(@Model.Editable ? "7" : "6")">No results found</td>
    </tr>
  }

  </tbody>
</table>

Views/Shared/_IndexHeader.cshtml
@model BoardGames.ViewModels.IndexHeaderViewModel;

<header class="row mt-5 mb-5">
  <div class="col-4 d-flex align-items-center">
    <h1>@Model.ControllerName</h1>
  </div>
  <div class="col-4 d-flex align-items-center justify-content-center">
    <form asp-controller="@Model.ControllerName" asp-action="Index" method="get">
      <div class="input-group">
        <input type="search" name="name" class="form-control" placeholder="Search by name" value="@TempData["SearchString"]">
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit" value="Filter">Search</button>
        </div>
      </div>
    </form>
  </div>
  <div class="col-4 d-flex align-items-center justify-content-end">
    @if (User.IsInRole("Admin"))
    {
      <a asp-area="" asp-controller="@Model.ControllerName" asp-action="Create" class="btn btn-primary">Add new</a>
    }
  </div>
</header>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - BoardGames</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="~/css/site.css"/>
  <script src="https://kit.fontawesome.com/1c64bcf471.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoardGames</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Publishers" asp-action="Index">Publishers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
          </li>
          
          @if (User.IsInRole("Admin"))
          {
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin tools
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
              </div>
            </li>
          }
        </ul>
        
        @if (signInManager.IsSignedIn(User))
        {
          <form asp-controller="Auth" asp-action="Logout" method="post">
            <button class="btn btn-primary"><span class="fas fa-sign-out-alt"></span> Logout</button>
          </form>
        }
        else
        {
          <a asp-controller="Auth" asp-action="Login" class="btn btn-primary"><span class="fas fa-user"></span> Login</a>
        }
      </div>
    </div>
  </nav>
</header>
<div class="container">
  <main role="main" class="pb-3">
    @RenderBody()
  </main>
</div>

<footer class="border-top footer text-muted">
  <p class="text-center m-0">Maciej Niedzielski ASP.NET Core MVC</p>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>